name: "CI"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Pulsar
      uses: pulsar-edit/action-pulsar-dependency@s985-update-win-path-registration
    
    - name: Install dependencies (Windows)
      if: ${{ runner.os == 'Windows' }}
      run: |
        $env:Path = (@(
          [System.Environment]::GetEnvironmentVariable("Path","Machine"),
          [System.Environment]::GetEnvironmentVariable("Path","User")
        ) -join ';')
        pulsar --package install
      
    - name: Install dependencies (*nix)
      if: ${{ runner.os != 'Windows' }}
      run: pulsar --package install
    
    - name: Run the headless Pulsar Tests (Windows)
      if: ${{ runner.os == 'Windows' }}
      uses: GabrielBB/xvfb-action@v1
      with:
        run: |
          $env:Path = (@(
            [System.Environment]::GetEnvironmentVariable("Path","Machine"),
            [System.Environment]::GetEnvironmentVariable("Path","User")
          ) -join ';')
          pulsar --test spec
        
    - name: Run the headless Pulsar Tests (*nix)
      if: ${{ runner.os != 'Windows' }}
      uses: GabrielBB/xvfb-action@v1
      with:
        run: pulsar --test spec

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: NPM install
        run: npm install
      - name: Lint ✨
        run: npm run lint

  Release:
    needs: [Test, Lint]
    if: |
      github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      #- uses: UziTech/action-setup-atom@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      
      - name: NPM install
        run: npm install
      
      - name: Release 🎉
        env:
          #Used to allow the CI to push a new release automatically. Intrinsic to GitHub CI.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #Used by ppm to auth for publishing of packages
          ATOM_ACCESS_TOKEN: ${{ secrets.PULSAR_ACCESS_TOKEN }}
        run: npx semantic-release
